(lazy-load-global-keys
 '(("C-h f" . helpful-callable)
   ("C-h k" . helpful-key)
   ("C-h v" . helpful-variable)
   ("C-h F" . helpful-function)
   ("C-h C" . help-command)) "helpful")

(advice-add 'helpful-update :after #'elisp-demos-advice-helpful-update)

(require 'helpful)
(add-hooks '(help-mode helpful-mode)
           #'visual-line-mode)
(keymap-sets helpful-mode-map
  '(("M-n" . scroll-up-1/3)
    ("M-p" . scroll-down-1/3)
    ("M-<left>" . (lambda ()
                    (interactive)
                    ;; (call-interactively #'toggle-window-dedicated)
                    (toggle-window-dedicated (get-buffer-window (current-buffer)) nil nil)
                    (previous-buffer)
                    ;; (call-interactively #'toggle-window-dedicated)
                    (toggle-window-dedicated (get-buffer-window (current-buffer)) t nil)
                    ))
    ("M-<right>" . (lambda ()
                     (interactive)
                     ;; (call-interactively #'toggle-window-dedicated)
                     (toggle-window-dedicated (get-buffer-window (current-buffer)) nil nil)
                     (next-buffer)
                     ;; (call-interactively #'toggle-window-dedicated)
                     (toggle-window-dedicated (get-buffer-window (current-buffer)) t nil)
                     ))))

(provide 'init-helpful)
